# Generated by Django 4.1.7 on 2023-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.CharField(blank=True, default='anonymous', max_length=100)),
                ('amount', models.IntegerField()),
                ('donate_to', models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Hunger', 'Hunger')], default='Hunger', max_length=100)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
