# Generated by Django 4.1.7 on 2023-03-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='sponsor',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
