# Generated by Django 4.1.7 on 2023-03-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestitutesEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.CharField(max_length=150)),
                ('familyname', models.CharField(max_length=100)),
                ('shortstory', models.CharField(max_length=250)),
                ('problemdescription', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('monthlybudget', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='DestitutesHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('patientsnames', models.CharField(max_length=100)),
                ('patientsage', models.IntegerField()),
                ('patientsphoto', models.ImageField(blank=True, upload_to='')),
                ('hospital', models.CharField(max_length=100)),
                ('medicalcondition', models.TextField(max_length=1000)),
                ('requiredfunds', models.IntegerField()),
                ('requiredtreatment', models.CharField(max_length=150)),
                ('urgent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
