# Generated by Django 4.1.7 on 2023-03-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destitutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destitutes',
            name='familyname',
            field=models.CharField(max_length=100),
        ),
    ]
