# Generated by Django 4.1.7 on 2023-03-18 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('location', models.CharField(choices=[('Copperbelt', 'Copperbelt'), ('Lusaka', 'Lusaka'), ('Central', 'Central'), ('North Western', 'North Western'), ('Luapula', 'Luapula'), ('Southern', 'Southern'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Muchinga', 'Muchinga'), ('Nothern', 'Northern')], max_length=100)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
