# Generated by Django 4.1.7 on 2023-03-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='highlighted',
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='location',
            field=models.CharField(choices=[('Copperbelt', 'Copperbelt'), ('Lusaka', 'Lusaka'), ('Central', 'Central'), ('North Western', 'North Western'), ('Luapula', 'Luapula'), ('Southern', 'Southern'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Muchinga', 'Muchinga'), ('Nothern', 'Northern')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='mobile',
            field=models.CharField(max_length=30),
        ),
    ]
